name: MyDockerAction
on: push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Dockercheck
      run: docker -v
    - name: Copy
      uses: actions/checkout@v3
    - name: Log in dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.SEKRET_DOCKER_LOGIN }}
        password: ${{ secrets.SEKRET_DOCKER_PASS }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: kok/MyDickerFlusk
