name: MyDockerAction
on: push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Dockercheck
      run: docker -v
    - name: Copy
      uses: actions/checkout@v3
    - name: Build Image
      run: docker build -t kok .
