name: MyFlask
on: workflow_dispatch
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run: |
          python -v
          pip3 install flask
    - name: Step2
      uses: actions/checkout@v3
    - name: Step3
      run: python hello.py
      
